# 数据源配置
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
# mybatis 配置
#mybatis:
#  mapper-locations: classpath:/mappers/*.xml # 扫描mybatis的实现dao接口*.xml文件
#  type-aliases-package: com.ppl.springboot.entity #实体类取别名
#  configuration:
#    # 下划线转驼峰配置
#    map-underscore-to-camel-case: true

comment.avatar: /image/avatar.png
