# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geneningz_blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
logging:
  level:
    root: warn
    geneningz.io: info
  file:
    name: log/blog-pro.log

server:
  port: 8081
