# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/geneningz_blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# mybatis 配置
#mybatis:
#  mapper-locations: classpath:/mappers/*.xml # 扫描mybatis的实现dao接口*.xml文件
#  type-aliases-package: com.ppl.springboot.entity #实体类取别名
#  configuration:
#    # 下划线转驼峰配置
#    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    geneningz.io: debug
  file:
    name: log/blog-dev.blog


server:
  port: 8081
